CREATE DATABASE concessionaria;
USE concessionaria;

CREATE TABLE Carro(ID INT AUTO_INCREMENT NOT NULL, Marca VARCHAR(50),  Modelo VARCHAR(50),Cor VARCHAR(50), Foto VARCHAR(50),  Descricao VARCHAR(100), Ano FLOAT, Preco FLOAT, PRIMARY KEY(ID));
